services:
  triton:
    build:
      context: .
      dockerfile: triton.Dockerfile
    ports:
      - "8000:8000"  # HTTP API
      - "8001:8001"  # gRPC API
      - "8002:8002"  # Metrics
    volumes:
      - ./ru_text_normalization/model_repository:/models:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]