name: "text_normalization"
backend: "python"
max_batch_size: 4

input [
    {
        name: "text"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]

output [
    {
        name: "output_text"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]