backend: "onnxruntime"
default_model_filename: "FRED_text_normalization_trans_onnx.onnx"
max_batch_size: 8

parameters {
  key: "model_type"
  value: {
    string_value: "T5"
  }
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

dynamic_batching {
  preferred_batch_size: [ 1, 4 ]
  max_queue_delay_microseconds: 100
}